blank_issues_enabled: true
contact_links:
  - name: Railroader Discord support thread
    url: "https://discord.com/channels/795878618697433097/1316066545352577145"
    about: Get help with Fleet Manager on the Railroader Discord.
